PROJECT = rabbitmq_prelaunch
PROJECT_DESCRIPTION = RabbitMQ prelaunch setup
PROJECT_VERSION = 0.1.0
PROJECT_MOD = rabbit_prelaunch_app

DEPS = rabbit_common lager cuttlefish

dep_cuttlefish = hex 2.2.0

DEP_PLUGINS = rabbit_common/mk/rabbitmq-build.mk

include ../../rabbitmq-components.mk
include ../../erlang.mk
